erofs-utils: use uint32_t instead of uint
uint is defined in <sys/types.h> header. It is usually included by <stdlib.h>
but in musl stdlib.h doesn't include it.

Fixes:

compress.c: In function ‘vle_compress_one’:
compress.c:209:10: error: unknown type name ‘uint’
    const uint qh_aligned = round_down(ctx->head, EROFS_BLKSIZ);
          ^~~~
compress.c:210:10: error: unknown type name ‘uint’
    const uint qh_after = ctx->head - qh_aligned;
          ^~~~
compress.c: In function ‘z_erofs_convert_to_compacted_format’:
compress.c:313:8: error: unknown type name ‘uint’
  const uint headerpos = Z_EROFS_VLE_EXTENT_ALIGN(inode->inode_isize +
        ^~~~
compress.c:316:8: error: unknown type name ‘uint’
  const uint totalidx = (legacymetasize -

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>